### ISSUE TITLE
Engine API Usage

### ISSUE THREAD

**Issue by wildmaster84** [ShiftyX1/java_voxel_engine#1]
How can i hook into the engine to start generating terrain?

**Comment by ShiftyX1** [comment]
Thanks for your interest! Actually, I decided not to reinvent the wheel and I'm currently contributing to VoxelEngine-Cpp (https://github.com/MihailRis/VoxelEngine-Cpp) instead. It's a solid voxel engine implementation, and I found it more valuable to contribute to an existing project rather than building everything from scratch. You should try it out! :D

**Comment by wildmaster84** [comment]
ah oki, although im more interested in coding in java.
